spring.application.name=meetingtracker

spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:35967/railway
spring.datasource.username=root
spring.datasource.password=IGrrIBiNEXgnwbXHUHkqBJcaafLsuuiS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true